name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: lukka/get-cmake@v3.21.2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libgtest-dev

      - name: Build and run tests
        run: |
          mkdir -p ie0217/Sesiones/Sesion16/unit_testing/build
          cd ie0217/Sesiones/Sesion16/unit_testing/build
          cmake ..
          make
          ./test_calculator

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: echo "Deploying to production server"
        # Acá se agrega el script real para desplegar la aplicación
