name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Instalar CMake
      # Paso 2: Clonar GoogleTest dentro de CalculatorProject
      - name: Clone GoogleTest
        run: |
          git clone https://github.com/google/googletest.git Laboratorios/Laboratorio10/googletest
      # Paso 3: Instalar CMake
      - name: Set up CMake
        uses: lukka/get-cmake@v3.21.2

      # Paso 3: Instalar dependencias necesarias
      # Paso 4: Instalar dependencias necesarias
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Paso 4: Clonar y compilar GoogleTest
      - name: Clone and build GoogleTest
        run: |
          git clone https://github.com/google/googletest.git
          mkdir -p Laboratorios/Laboratorio10/googletest/build
          cd Laboratorios/Laboratorio10/googletest/build
          cmake ..
          make
          sudo cp lib/*.a /usr/local/lib  # Copia las bibliotecas de GoogleTest
      # Paso 5: Crear directorio de compilación y compilar el proyecto
      - name: Build project
        run: |
          mkdir -p Laboratorios/Laboratorio10/googletest/build
          cd Laboratorios/Laboratorio10/googletest/build
          cmake ..
          make
      # Paso 6: Ejecutar las pruebas
      - name: Run tests
        run: |
          cd Laboratorios/Laboratorio10/build/tests
          ./run_tests