name: Tarea7 CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar GoogleTest y dependencias
      - name: Clone and build GoogleTest
        run: |
          git clone https://github.com/google/googletest.git Tareas/Tarea7/googletest
          mkdir -p Tareas/Tarea7/googletest/build
          cd Tareas/Tarea7/googletest/build
          cmake ..
          make
          sudo cp lib/*.a /usr/local/lib  # Copia las bibliotecas de GoogleTest

      # Paso 3: Instalar herramientas de desarrollo necesarias lcov
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential lcov

      # Paso 4: Configurar y construir el proyecto
      - name: Build project
        run: |
          mkdir -p Tareas/Tarea7/build
          cd Tareas/Tarea7/build
          cmake ..
          make

      # Paso 5: Ejecutar pruebas unitarias
      - name: Run tests
        run: |
          cd Tareas/Tarea7/build/tests
          ./InventarioTests
          ./InventarioFunctionalTests
          ./ComponenteTests
          ./CircuitosTests

      # Paso 6: Generar reporte de cobertura de código
      - name: Generate coverage report
        run: |
          cd Tareas/Tarea7/build
          lcov --capture --directory . --output-file coverage.info --exclude '*/googletest/*' --exclude '/usr/include/*'
          genhtml coverage.info --output-directory coverage-report
          echo "Coverage report generado en el directorio Tareas/Tarea7/build/coverage-report"

      # Paso 7: Subir el reporte de cobertura como artefacto
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: Tareas/Tarea7/build/coverage-report

  simulate-deployment:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ success() }}

    steps:
      - name: Deployment Step
        run: echo "Despliegue exitoso."
